version: "3.5"
services:
  web:
    image: python:3.10-alpine
    build: resources/web
    container_name: web
    depends_on:
      - kafka
    ports:
      - "5001:5001"
    volumes:
      - /home/ibdn/Documents/LAB_final/practica_creativa:/project
    environment:
      PROJECT_HOME: /project
    command: >
      sh -c "pip install --upgrade pip && \
        pip install -r /project/requirements.txt"
    command: 
      sh -c " sleep 30 && python3 /project/resources/web/predict_flask.py"
    networks:
      - net-bridge

  mongo:
    image: mongo:4.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - /home/ibdn/Documents/LAB_final/practica_creativa/mongo_data:/DB
    networks:
      - net-bridge
  
  mongo-seed:
    image: mongo:4.0
    container_name: mongo-seed
    links:
      - mongo
    volumes:
      - /home/ibdn/Documents/LAB_final/practica_creativa:/project
    command: 
      /project/resources/import_distances.sh && echo "[!] DATA IMPORTED!"
    networks:
      - net-bridge

  zookeeper_kafka:
    image: confluentinc/cp-zookeeper:latest
    container_name: kfk_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181
    networks:
      - net-bridge

  kafka:
    image: confluentinc/cp-kafka:3.3.3
    container_name: kafka
    depends_on:
      - zookeeper_kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_kafka:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://loclahost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_REPLICATION_FACTOR: 1
    volumes:
      - /home/ibdn/Documents/LAB_final/practica_creativa:/project
    networks:
      - net-bridge
    command: 
      - /project/kafka_2.12-3.4.0/start_kafka.sh
  
  spark-master:
    image: bde2020/spark-master:3.2.1-hadoop3.2
    container_name: spark-master
    ports:
      - "7077:7077"
      - "9001:9001"
      - "8080:8080"
    environment:
      - "SPARK_MASTER=${SPARK_MASTER}"
      - "INIT_DAEMON_STEP=setup_spark"
      - "constraint:node==spark-master"
      - "SERVER=${SERVER}"
    volumes:
      - /home/ibdn/Documents/LAB_final/practica_creativa:/project

  spark-worker1:
    image: bde2020/spark-worker:3.2.1-hadoop3.2
    container_name: spark-worker1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=${SPARK_MASTER}"
      - "INIT_DAEMON_STEP=setup_spark"
      - "constraint:node==spark-master"
      - "SERVER=${SERVER}"
    volumes:
      - /home/ibdn/Documents/LAB_final/practica_creativa:/project

  spark-worker2:
    image: bde2020/spark-worker:3.2.1-hadoop3.2
    container_name: spark-worker2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=${SPARK_MASTER}"
      - "INIT_DAEMON_STEP=setup_spark"
      - "constraint:node==spark-master"
      - "SERVER=${SERVER}"
    volumes:
      - /home/ibdn/Documents/LAB_final/practica_creativa:/project

  spark-submit:
    image: bitnami/spark:3.3.3
    container_name: spark-submit
    depends_on:
      - spark-master
      - spark-worker1
      - spark-worker2
    ports:
      - "4040:4040"
    environment:
      - "SPARK_MASTER=${SPARK_MASTER}"
      - "constraint:node==spark-mastyer"
      - "SERVER=${SERVER}"
    volumes:
      - /home/ibdn/Documents/LAB_final/practica_creativa:/project/
    command: >
      sh -c "sleep 15; spark-submit --class es.upm.dit.ging.predictor.MakePrediction --master local[*] \
      --packages org.mongodb.spark:mongo-spark-connector_2.12:10.1.1,org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.0 \
      /project/flight_prediction/target/scala-2.12/flight_prediction_2.12-0.1.jar"
    networks:
      - net-bridge

networks:
  net-bridge:
    driver: bridge
      