apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file ../compose.yaml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file ../compose.yaml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/net-bridge: "true"
        io.kompose.service: kafka
    spec:
      containers:
        - args:
            - /project/kafka_2.12-3.4.0/start_kafka.sh
          env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://loclahost:29092
            - name: KAFKA_BROKER_ID
              value: "0"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - name: KAFKA_OFFSETS_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper_kafka:2181
          image: confluentinc/cp-kafka:3.3.3
          name: kafka
          ports:
            - containerPort: 9092
          resources: {}
          volumeMounts:
            - name : project-volume
              mountPath: /project
      volumes:
      - name: project-volume
        hostPath:
          path: /home/marti_costa_mart/Projecte_final_BDFI  # Path on the host machine
          type: Directory       # Ensures it is a directory
      restartPolicy: Always
status: {}
